### ISSUE TITLE
Automatically Deleting Old Temporary Models

### ISSUE THREAD

**Issue by MathieuDehouck** [zysite/biaffine-parser#14]
Hello,

First of all, thank you very much for your work.
I use your parser a lot lately.

I had a wonder though.
When I train a lot of parsers on very small data sets, I'm left with thousands of saved models.
Is there a way to automatically delete those past models and only keep the latest one?

Thank you very much

**Comment by zysite** [comment]
Hi
Thank you for your reply
My latest commit has solved this problem
