### ISSUE TITLE
Data Download for Testing

### ISSUE THREAD

**Issue by pranoy-k** [zysite/biaffine-parser#4]
Can you share some information on the data availability for testing, I want to inculcate this model in a different project so would like to quickly test and understanding the working. Can you share an open source data source?

**Comment by pranoy-k** [comment]
I was able to figure out, thanks

**Comment by zysite** [comment]
NLTK has sample data

**Comment by pranoy-k** [comment]
Yeah Exactly used the same, thanks for replying back
