### ISSUE TITLE
Apply MST when evaluating or predicting?

### ISSUE THREAD

**Issue by tysonyuu** [zysite/biaffine-parser#6]
Hi, I found that it seems that you didn't apply MST when evaluating or predicting.
In parser/model.py, the decoding function directly uses Argmax function instead of MST algorithm.
It means that it will yield illegal dependency parsing result when predicting.
Am I correct?   Thank you

**Comment by zysite** [comment]
Yes, the MST algorithm has not been implemented yet

**Comment by tysonyuu** [comment]
OK, thank you for your reply.
