### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by zhentaoCoding** [zysite/biaffine-parser#7]
why  I get this problem
![image](https://user-images.githubusercontent.com/5669444/56849492-b8686080-6927-11e9-97a0-4847ad9ab0ec.png)

**Comment by zysite** [comment]
Sorry, but can you give me more details, e.g., the command you typed

**Comment by zhentaoCoding** [comment]
I want to debug in pycharm ,so I run the run.py file

**Comment by zysite** [comment]
I ran the code myself, and it works

**Comment by zysite** [comment]
Here is the [solution](9).
