### ISSUE TITLE
Duplicate Name "parser"

### ISSUE THREAD

**Issue by shellywhen** [zysite/biaffine-parser#9]
I get an error when running `run.py`

> ModuleNotFoundError: No module named 'parser.cmds'; 'parser' is not a package

I suppose the reason is that one module is named "parser" while one file is named "parser".

**Comment by zysite** [comment]
This might be the case, but I still haven't encountered this problem. I'll check it latter.
If you solve it, can you tell me where is the problem?

**Comment by shellywhen** [comment]
Yes. I changed the module name and modified the relevant codes slightly and it works now. Currently, I am facing another problem with encoding...

**Comment by zysite** [comment]
Did you run it on windows?
Just now I re-clone the repo and run the code on both the Ubuntu server and windows 10 WSL, and there was still no problems. Since there are no computation resources on my windows machine, I didn't test the code on windows carefully.

**Comment by shellywhen** [comment]
Yeah I am running on a win10 machine with `python 3.7.3`

**Comment by zysite** [comment]
OK, I will fix this bug later, thanks.
